services:
  - type: web
    name: temporary-chat-application-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: web
    name: temporary-chat-application
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
    publishDir: client/dist
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-store
    routes:
      - type: rewrite
        source: /**
        destination: /index.html 